server:
  port: 8081

spring:
  application:
    name: spring-grpc-client

api:
  client:
    name: spring-grpc-server
    address: "localhost:9090"

grpc:
  client:
    GLOBAL:
      address: ${api.client.address}
      negotiation-type: PLAINTEXT

